import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { knowledgeApi, type KnowledgeRecord, type KnowledgeRecordKind, type KnowledgeVersion } from '@/services/knowledgeApi';
import { validateKnowledgeRecord } from '../../../supabase/functions/_shared/knowledgeSchema';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const titles:Record<KnowledgeRecordKind,string>={document:'Source documents',skill:'Extracted skills',mapping:'Framework mappings',job:'Job profiles'};
const template=(kind:KnowledgeRecordKind)=>kind==='document'?{text:'',url:'',documentType:'document'}:kind==='skill'?{description:'',framework:'',category:'',level:'',evidence:[{documentId:'',version:1,quote:''}]}:kind==='mapping'?{skillId:'',framework:'',category:'',level:''}:{description:'',requirements:[{skillId:'',level:'',category:''}]};
export default function SkillWorkspace({storeId,organizationId,pageId,initialView='document'}:{storeId:string;organizationId:string;pageId?:string;initialView?:KnowledgeRecordKind}){
 const {user}=useAuth();const client=useQueryClient();const [view,setView]=useState<KnowledgeRecordKind>(initialView);const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<KnowledgeRecord|null>(null);const [creating,setCreating]=useState(false);const [name,setName]=useState('');const [body,setBody]=useState('');const [archive,setArchive]=useState<KnowledgeRecord|null>(null);
 const [historyId,setHistoryId]=useState('');const [query,setQuery]=useState('');const [matches,setMatches]=useState<Awaited<ReturnType<typeof knowledgeApi>>['matches']>([]);const [workflow,setWorkflow]=useState('');const [request,setRequest]=useState('{}');const [review,setReview]=useState<{id:string;records:unknown}|null>(null);const [graphOpen,setGraphOpen]=useState(false);
 const key=['knowledge-workspace',user?.id,organizationId,storeId,pageId];
 const snapshot=useQuery({queryKey:[...key,view,offset],queryFn:()=>knowledgeApi('snapshot',organizationId,{storeId,pageId,kind:view,offset}),refetchInterval:10000,retry:false});
 const history=useQuery({queryKey:[...key,'history',historyId],enabled:Boolean(historyId),queryFn:()=>knowledgeApi('history',organizationId,{storeId,pageId,id:historyId})});
 const graph=useQuery({queryKey:[...key,'graph'],enabled:graphOpen,queryFn:()=>knowledgeApi('graph',organizationId,{storeId,pageId})});
 const perform=async(action:string,data:Record<string,unknown>={})=>{setBusy(true);setError('');try{const result=await knowledgeApi(action,organizationId,{storeId,pageId,...data});await client.invalidateQueries({queryKey:key});return result;}catch(cause){setError(cause instanceof Error?cause.message:String(cause));return null;}finally{setBusy(false);}};
 const edit=(record?:KnowledgeRecord)=>{setEditing(record||null);setCreating(!record);setName(record?.name||'');setBody(JSON.stringify(record?.body||template(view),null,2));setError('');};
 const save=async()=>{try{const record=validateKnowledgeRecord({kind:view,name,body:JSON.parse(body)});if(await perform('save_record',{id:editing?.id,expectedRevision:editing?.revision,record})){setEditing(null);setCreating(false);}}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
 const data=snapshot.data;
 if(snapshot.error)return <p role="alert" className="p-4 text-destructive">{snapshot.error.message}</p>;
 if(!data)return <p role="status">Loading skill workspace…</p>;
 return <section aria-label="Skill workspace" className="min-w-0 space-y-4">
  <div className="flex flex-wrap items-center gap-2"><h2 className="mr-auto text-xl font-semibold">{data.store?.name}</h2><Button variant="outline" onClick={()=>void snapshot.refetch()}>Refresh knowledge</Button><Button variant="outline" onClick={()=>setGraphOpen(true)}>Traceable graph</Button></div>
  {!pageId&&<nav aria-label="Skill application pages" className="flex flex-wrap gap-2">{(Object.keys(titles) as KnowledgeRecordKind[]).map(kind=><Button key={kind} variant={view===kind?'default':'outline'} onClick={()=>{setView(kind);setOffset(0);setCreating(false);setEditing(null);}}>{titles[kind]}</Button>)}</nav>}
  {error&&<p role="alert" className="text-destructive">{error}</p>}
  {data.canWrite&&<Button onClick={()=>edit()}>Add {view}</Button>}
  {!data.canWrite&&<p className="text-sm text-muted-foreground">Read-only workspace. An administrator can enable member editing for this store.</p>}
  <div className="overflow-auto"><table className="min-w-[840px] w-full text-left text-sm"><thead><tr><th className="p-2">Name</th><th className="p-2">Details</th><th className="p-2">Revision / actor</th><th className="p-2">Actions</th></tr></thead><tbody>{data.records?.map(record=><tr key={record.id} className="border-t"><td className="min-w-40 p-2"><strong>{record.name}</strong><p className="break-all text-xs text-muted-foreground">{record.id}</p></td><td className="max-w-md p-2"><details><summary>View {record.kind} data</summary><pre className="max-h-60 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(record.body,null,2)}</pre></details></td><td className="p-2"><p>v{record.revision} · {new Date(record.updated_at).toLocaleString()}</p><p className="break-all text-xs">{record.updated_by}</p></td><td className="p-2"><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setHistoryId(record.id)}>History & evidence</Button>{data.canWrite&&<><Button size="sm" variant="outline" onClick={()=>edit(record)}>Edit record</Button><Button size="sm" variant="destructive" onClick={()=>setArchive(record)}>Archive record</Button></>}</div></td></tr>)}</tbody></table>{!data.records?.length&&<p className="p-4 text-muted-foreground">No {titles[view].toLowerCase()} yet.</p>}</div>
  <div className="flex gap-2"><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous records</Button><Button variant="outline" disabled={data.nextOffset==null} onClick={()=>setOffset(data.nextOffset!)}>Next records</Button></div>
  {(creating||editing)&&<div className="space-y-3 rounded border p-4"><h3 className="font-semibold">{editing?'Edit':'Add'} {view}</h3><Label htmlFor={`record-name-${storeId}`}>Record name</Label><Input id={`record-name-${storeId}`} value={name} onChange={event=>setName(event.target.value)}/>{view==='document'&&<><Label>Import text document</Label><input aria-label="Import text document" type="file" accept=".txt,.md,.csv,.json" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>400000){setError('Text documents must be at most 400 KB.');return;}setName(file.name);setBody(JSON.stringify({text:await file.text(),url:'',documentType:file.name.split('.').pop()},null,2));}}/></>}<Label htmlFor={`record-body-${storeId}`}>Record fields (JSON)</Label><Textarea id={`record-body-${storeId}`} className="min-h-60 font-mono text-xs" value={body} onChange={event=>setBody(event.target.value)}/><p className="text-xs text-muted-foreground">Skills require evidence with documentId, version and an exact quote. Mappings and job requirements reference saved skill IDs. Source URLs are recorded as evidence locations; import their text through a configured workflow.</p><div className="flex gap-2"><Button disabled={busy} onClick={()=>void save()}>Save record</Button><Button variant="outline" onClick={()=>{setCreating(false);setEditing(null);}}>Cancel edit</Button></div></div>}
  <details className="rounded border p-3"><summary className="cursor-pointer font-medium">Search knowledge</summary><div className="mt-3 flex gap-2"><Input aria-label="Knowledge query" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search source evidence"/><Button disabled={busy||!query.trim()} onClick={async()=>{const result=await perform('query',{query});if(result)setMatches(result.matches);}}>Search</Button></div>{matches?.map((match,index)=><blockquote key={index} className="mt-3 border-l-2 pl-3 text-sm"><p>{match.content}</p><footer className="break-all text-xs text-muted-foreground">{match.documentId||match.sourceId} {match.revision&&`· revision ${match.revision}`}</footer></blockquote>)}</details>
  <details className="rounded border p-3" open={Boolean(data.jobs?.length)}><summary className="cursor-pointer font-medium">Knowledge operations</summary>{data.canWrite&&<div className="my-3 space-y-2"><Label htmlFor={`knowledge-workflow-${storeId}`}>Build workflow</Label><select id={`knowledge-workflow-${storeId}`} className="w-full rounded border bg-background p-2" value={workflow} onChange={event=>setWorkflow(event.target.value)}><option value="">Select assigned workflow</option>{data.store?.settings.workflowIds.map(id=><option key={id}>{id}</option>)}</select><Label htmlFor={`build-input-${storeId}`}>Build request (JSON)</Label><Textarea id={`build-input-${storeId}`} className="font-mono text-xs" value={request} onChange={event=>setRequest(event.target.value)}/><Button disabled={busy||!workflow} onClick={()=>{try{void perform('queue',{workflowId:workflow,input:JSON.parse(request)});}catch{setError('Build request must be valid JSON.');}}}>Queue build</Button><p className="text-xs text-muted-foreground">Include document IDs/revisions, a prompt or source URL for your workflow. Changed source documents queue the configured change workflow automatically.</p></div>}{data.jobs?.map(job=><div key={job.id} className="mt-2 flex flex-wrap items-center gap-3 rounded border p-2 text-sm"><span>{job.workflow_id} · {job.status}</span><span className="break-all text-xs">{job.run_id||'Awaiting dispatcher'}</span>{job.error&&<p className="text-destructive">{job.error}</p>}{job.status==='review'&&<Button size="sm" disabled={busy} onClick={async()=>{const result=await perform('review_job',{id:job.id});if(result)setReview({id:job.id,records:result.records});}}>Review generated records</Button>}</div>)}</details>
  <Dialog open={Boolean(archive)} onOpenChange={open=>{if(!open)setArchive(null);}}><DialogContent><DialogHeader><DialogTitle>Archive {archive?.name}?</DialogTitle><DialogDescription>Removes this record from current listings and retrieval. Revision history and existing evidence citations remain traceable.</DialogDescription></DialogHeader><Button variant="destructive" disabled={busy} onClick={async()=>{if(await perform('delete_record',{id:archive?.id,expectedRevision:archive?.revision}))setArchive(null);}}>Confirm archive</Button>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
  <Dialog open={Boolean(historyId)} onOpenChange={open=>{if(!open)setHistoryId('');}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Record provenance</DialogTitle><DialogDescription>Source revisions, actors, timestamps, and extraction/classification workflow runs.</DialogDescription></DialogHeader>{history.isPending&&<p>Loading history…</p>}{history.error&&<p role="alert">{history.error.message}</p>}{history.data?.versions?.map((version:KnowledgeVersion)=><section key={version.id} className="space-y-2 rounded border p-3"><h3 className="font-medium">{version.name} · revision {version.revision}{version.deleted?' · archived':''}</h3><p className="break-all text-xs">{version.created_at} · actor {version.actor_id} · workflow {version.workflow_context?.workflowName || version.workflow_context?.workflowId || ''} {version.workflow_run_id||'manual change'}</p><pre className="max-h-60 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(version.body,null,2)}</pre>{Array.isArray(version.body.evidence)&&version.body.evidence.map((raw,index)=>{const evidence=raw as {documentId:string;version:number};return <Button key={index} size="sm" variant="outline" onClick={()=>setHistoryId(evidence.documentId)}>Source revision {evidence.version}</Button>;})}</section>)}</DialogContent></Dialog>
  <Dialog open={Boolean(review)} onOpenChange={open=>{if(!open)setReview(null);}}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Review generated knowledge</DialogTitle><DialogDescription>Applying imports these records atomically. Source evidence and skill references are checked before committing.</DialogDescription></DialogHeader><pre className="max-h-96 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(review?.records,null,2)}</pre><Button disabled={busy||!data.canWrite} onClick={async()=>{if(await perform('apply_job',{id:review?.id}))setReview(null);}}>Apply reviewed records</Button>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
  <Dialog open={graphOpen} onOpenChange={setGraphOpen}><DialogContent className="max-h-[85vh] overflow-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Traceable skill graph</DialogTitle><DialogDescription>Job profiles → skills → document revisions; framework mappings → skills. Showing up to 500 nodes and 1,000 edges.</DialogDescription></DialogHeader>{graph.error&&<p role="alert">{graph.error.message}</p>}{graph.data?.edges?.map((edge,index)=><div className="flex flex-wrap items-center gap-2 rounded border p-2 text-sm" key={index}><Button variant="link" onClick={()=>{setGraphOpen(false);setHistoryId(edge.source_id);}}>{graph.data?.nodes?.find(node=>node.id===edge.source_id)?.name||edge.source_id}</Button><span>→ {edge.relation.replace(/_/g,' ')} →</span><Button variant="link" onClick={()=>{setGraphOpen(false);setHistoryId(edge.target_id);}}>{graph.data?.nodes?.find(node=>node.id===edge.target_id)?.name||edge.target_id} · v{edge.target_revision}</Button></div>)}{!graph.data?.edges?.length&&<p>No evidence links yet.</p>}</DialogContent></Dialog>
 </section>;
}
