import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/contexts/AuthContext';
import { knowledgeApi, newKnowledgeStore, type KnowledgeStore } from '@/services/knowledgeApi';
import { validateKnowledgeStore } from '../../../supabase/functions/_shared/knowledgeSchema';
import SkillWorkspace from '@/components/knowledge/SkillWorkspace';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
export default function KnowledgeManagement(){
 const {user}=useAuth();const orgId=user?.organization?.id;const client=useQueryClient();const key=['knowledge-stores',user?.id,orgId];
 const query=useQuery({queryKey:key,enabled:Boolean(orgId),queryFn:()=>knowledgeApi('list',orgId)});
 const [selected,setSelected]=useState<KnowledgeStore|null>(null);const [creating,setCreating]=useState(false);const [source,setSource]=useState(JSON.stringify(newKnowledgeStore(),null,2));const [token,setToken]=useState('');const [clearSecret,setClearSecret]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [workspace,setWorkspace]=useState('');const [archive,setArchive]=useState<KnowledgeStore|null>(null);const [appUrl,setAppUrl]=useState('');
 const perform=async(action:string,body:Record<string,unknown>)=>{setBusy(true);setError('');try{const result=await knowledgeApi(action,orgId,body);await client.invalidateQueries({queryKey:key});return result;}catch(cause){setError(cause instanceof Error?cause.message:String(cause));return null;}finally{setBusy(false);}};
 const edit=(store?:KnowledgeStore)=>{setSelected(store||null);setCreating(!store);setSource(JSON.stringify(store||newKnowledgeStore(),null,2));setToken('');setClearSecret(false);setError('');};
 let draft = newKnowledgeStore();
 try { const value=JSON.parse(source); draft={...draft,...value,settings:{...draft.settings,...value.settings}}; } catch { /* raw JSON remains editable */ }
 const field=(name:string,value:unknown)=>{try{setSource(JSON.stringify({...JSON.parse(source),[name]:value},null,2));}catch{setError('Correct configuration JSON before using form fields.');}};
 const save=async()=>{try{const store=validateKnowledgeStore(JSON.parse(source));if(await perform(creating?'create_store':'save_store',{storeId:selected?.id,expectedRevision:selected?.revision,store,token,clearSecret})){setSelected(null);setCreating(false);setToken('');}}catch(cause){setError(cause instanceof Error?cause.message:String(cause));}};
 return <div className="space-y-5"><Card><CardHeader><CardTitle>Knowledge & Skills</CardTitle><CardDescription>Manage RAG, knowledge graph and vector connections. Build a skill application backed by versioned source evidence.</CardDescription></CardHeader><CardContent><Button onClick={()=>edit()}>New knowledge store</Button></CardContent></Card>
 {(error||query.error)&&<p role="alert" className="text-destructive">{error||query.error?.message}</p>}{query.isPending&&<p>Loading knowledge stores…</p>}
 {query.data?.stores?.map(store=><Card key={store.id}><CardContent className="space-y-3 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{store.name}</h3><span className="text-sm">{store.kind} · {store.provider} · {store.active?'Active':'Inactive'}</span></div><p className="break-all text-xs text-muted-foreground">{store.id} · revision {store.revision} · credentials {store.credentialConfigured?'configured':'not configured'}</p><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>edit(store)}>Configure</Button><Button variant="outline" disabled={busy} onClick={()=>void perform('save_store',{storeId:store.id,expectedRevision:store.revision,store:{...store,active:!store.active}})}>{store.active?'Deactivate':'Activate'}</Button><Button variant="outline" onClick={()=>setWorkspace(workspace===store.id?'':store.id)}>Open skill workspace</Button><Button disabled={busy||!store.active} onClick={async()=>{const result=await perform('create_skill_app',{storeId:store.id});if(result?.slug)setAppUrl(`/o/${user?.organization?.slug}/apps/${result.slug}`);}}>Create skill application</Button><Button variant="destructive" disabled={busy} onClick={()=>setArchive(store)}>Archive store</Button></div></CardContent></Card>)}
 {appUrl&&<p>Skill application ready: <a className="underline" href={appUrl} target="_blank" rel="noopener noreferrer">Open application</a>. Its four pages can be edited in Applications & Pages.</p>}
 {(creating||selected)&&<Card><CardHeader><CardTitle>{creating?'Create knowledge store':`Configure ${selected?.name}`}</CardTitle><CardDescription>Settings bind this store to page, agent and workflow IDs. A changeWorkflowId queues builds when source documents change. memberWrites enables organization members to edit records.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="knowledge-name">Store name</Label><Input id="knowledge-name" value={typeof draft.name==='string'?draft.name:''} onChange={event=>field('name',event.target.value)}/></div><div><Label htmlFor="knowledge-kind">Store type</Label><select id="knowledge-kind" className="w-full rounded border bg-background p-2" value={draft.kind} onChange={event=>field('kind',event.target.value)}><option value="rag">RAG document retrieval</option><option value="knowledge_graph">Knowledge graph</option><option value="vector">Vector database</option></select></div><div><Label htmlFor="knowledge-provider">Provider</Label><select id="knowledge-provider" className="w-full rounded border bg-background p-2" value={draft.provider} onChange={event=>field('provider',event.target.value)}><option value="managed">Managed documents and graph</option><option value="rest">Secure REST adapter</option></select></div><div><Label htmlFor="knowledge-endpoint">REST endpoint</Label><Input id="knowledge-endpoint" value={typeof draft.endpoint==='string'?draft.endpoint:''} onChange={event=>field('endpoint',event.target.value)} placeholder="https://adapter.example/query"/></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.active===true} onChange={event=>field('active',event.target.checked)}/>Store active</label><Label htmlFor="knowledge-config">Store configuration (JSON)</Label><Textarea id="knowledge-config" className="min-h-80 font-mono text-xs" value={source} onChange={event=>setSource(event.target.value)}/><Label htmlFor="knowledge-token">REST bearer token (leave blank to retain)</Label><Input id="knowledge-token" type="password" autoComplete="new-password" value={token} onChange={event=>setToken(event.target.value)}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={clearSecret} onChange={event=>setClearSecret(event.target.checked)}/>Clear stored connector credential</label><p className="text-xs text-muted-foreground">Managed stores index source text and maintain evidence graphs. Vector retrieval requires a REST adapter returning matches. REST endpoints require HTTPS and a server-side KNOWLEDGE_REST_ALLOWED_HOSTS entry. Credentials are encrypted and never returned.</p><div className="flex gap-2"><Button disabled={busy} onClick={()=>void save()}>Save knowledge store</Button><Button variant="outline" onClick={()=>{setCreating(false);setSelected(null);setToken('');}}>Cancel configuration</Button></div></CardContent></Card>}
 {workspace&&orgId&&<Card><CardContent className="p-4"><SkillWorkspace key={workspace} storeId={workspace} organizationId={orgId}/></CardContent></Card>}
 <Dialog open={Boolean(archive)} onOpenChange={open=>{if(!open)setArchive(null);}}><DialogContent><DialogHeader><DialogTitle>Archive {archive?.name}?</DialogTitle><DialogDescription>Disables retrieval and editing while retaining evidence history. Assigned components become unavailable.</DialogDescription></DialogHeader><Button variant="destructive" disabled={busy} onClick={async()=>{if(await perform('delete_store',{storeId:archive?.id,expectedRevision:archive?.revision})){setArchive(null);setWorkspace('');}}}>Confirm archive store</Button>{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
 </div>;
}
