\set ON_ERROR_STOP on
begin;
insert into auth.users(id) values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
insert into organizations(id,slug,name) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','knowledge-test','Knowledge'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','other-test','Other');
insert into organization_members values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','active'),('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','22222222-2222-4222-8222-222222222222','active');
insert into user_roles values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','11111111-1111-4111-8111-111111111111','admin');
do $$
declare o uuid:='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';a uuid:='11111111-1111-4111-8111-111111111111';m uuid:='22222222-2222-4222-8222-222222222222';s jsonb;d jsonb;k jsonb;v jsonb;app jsonb;bad boolean;sid uuid;did uuid;kid uuid;jid uuid;rid uuid;before_count integer;
begin
 if has_table_privilege('authenticated','knowledge_records','SELECT') or has_table_privilege('anon','knowledge_stores','SELECT') or has_function_privilege('authenticated','knowledge_mutate(uuid,uuid,text,uuid,uuid,integer,jsonb,text,uuid)','EXECUTE') then raise exception 'Knowledge tables exposed';end if;
 s:=knowledge_mutate(o,a,'create_store',null,null,null,'{"name":"Skill graph","kind":"knowledge_graph","provider":"managed","endpoint":"","active":true,"settings":{"pageIds":[],"agentIds":[],"workflowIds":["extract"],"changeWorkflowId":"extract","memberWrites":false}}');sid:=(s->>'id')::uuid;
 bad:=false;begin perform knowledge_mutate(o,m,'save_record',sid,null,null,'{"kind":"document","name":"Not allowed","body":{"text":"No"}}');exception when insufficient_privilege then bad:=true;end;if not bad then raise exception 'Member wrote to admin store';end if;
 d:=knowledge_mutate(o,a,'save_record',sid,null,null,'{"kind":"document","name":"Source A","body":{"text":"Planning and analysis skills are needed.","url":"https://example.com/doc","documentType":"course"}}');did:=(d->>'id')::uuid;
 if (select count(*) from knowledge_jobs where store_id=sid)<>1 then raise exception 'Document change did not queue a job';end if;
 if jsonb_array_length(knowledge_search(o,sid,'analysis'))<>1 then raise exception 'Retrieval failed';end if;
 if jsonb_array_length(knowledge_search('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sid,'analysis'))<>0 then raise exception 'Cross tenant retrieval';end if;
 k:=knowledge_mutate(o,a,'save_record',sid,null,null,jsonb_build_object('kind','skill','name','Analysis','body',jsonb_build_object('description','Analyze','evidence',jsonb_build_array(jsonb_build_object('documentId',did,'version',1,'quote','analysis skills')))));kid:=(k->>'id')::uuid;
 if (select count(*) from knowledge_edges where source_id=kid)<>1 then raise exception 'Evidence edge missing';end if;
 bad:=false;begin perform knowledge_mutate(o,a,'save_record',sid,null,null,jsonb_build_object('kind','skill','name','Invented','body',jsonb_build_object('evidence',jsonb_build_array(jsonb_build_object('documentId',did,'version',1,'quote','fabricated quote')))));exception when others then bad:=true;end;if not bad then raise exception 'Fabricated citation accepted';end if;
 bad:=false;begin perform knowledge_mutate(o,a,'save_record',sid,did,99,'{"kind":"document","name":"Overwrite","body":{"text":"Wrong"}}');exception when serialization_failure then bad:=true;end;if not bad then raise exception 'Stale update accepted';end if;
 d:=knowledge_mutate(o,a,'save_record',sid,did,1,'{"kind":"document","name":"Source A revised","body":{"text":"Updated source about research."}}');
 if jsonb_array_length(knowledge_search(o,sid,'analysis'))<>0 then raise exception 'Stale chunks still retrievable';end if;
 if not exists(select 1 from knowledge_versions where record_id=did and revision=1 and body->>'text' like '%analysis%') then raise exception 'Source revision lost';end if;
 v:=knowledge_mutate(o,a,'save_record',sid,null,null,jsonb_build_object('kind','mapping','name','Framework mapping','body',jsonb_build_object('skillId',kid,'framework','Internal','category','Analysis','level','Advanced')));
 v:=knowledge_mutate(o,a,'save_record',sid,null,null,jsonb_build_object('kind','job','name','Analyst','body',jsonb_build_object('description','Analyze data','requirements',jsonb_build_array(jsonb_build_object('skillId',kid,'level','Advanced','category','Analysis')))));
 if (select count(*) from knowledge_edges where store_id=sid)<>3 then raise exception 'Skill graph missing relationships';end if;
 app:=knowledge_create_skill_app(o,a,sid);
 if (select count(*) from studio_items where parent_id=(app->>'applicationId')::uuid and active)<>4 then raise exception 'Template did not publish four pages';end if;
 if knowledge_create_skill_app(o,a,sid)->>'applicationId'<>app->>'applicationId' then raise exception 'Template is not idempotent';end if;
 if jsonb_array_length((select settings->'pageIds' from knowledge_stores where id=sid))<>4 then raise exception 'Page bindings missing';end if;
 insert into workflow_runs(organization_id,status,output) values(o,'succeeded','{}') returning id into rid;
 insert into knowledge_jobs(organization_id,store_id,actor_id,workflow_id,input,status,run_id) values(o,sid,a,'extract','{}','review',rid) returning id into jid;
 select count(*) into before_count from knowledge_records where store_id=sid;
 bad:=false;begin perform knowledge_mutate(o,a,'apply_job',sid,jid,null,jsonb_build_object('records',jsonb_build_array(jsonb_build_object('kind','skill','name','Valid first','body',jsonb_build_object('evidence',jsonb_build_array(jsonb_build_object('documentId',did,'version',1,'quote','analysis skills')))),jsonb_build_object('kind','skill','name','Invalid second','body',jsonb_build_object('evidence',jsonb_build_array(jsonb_build_object('documentId',did,'version',1,'quote','invented')))))));exception when others then bad:=true;end;
 if not bad or (select count(*) from knowledge_records where store_id=sid)<>before_count then raise exception 'Partial workflow import committed';end if;
 v:=knowledge_mutate(o,a,'apply_job',sid,jid,null,jsonb_build_object('records',jsonb_build_array(jsonb_build_object('kind','skill','name','Imported','body',jsonb_build_object('evidence',jsonb_build_array(jsonb_build_object('documentId',did,'version',1,'quote','analysis skills')))))));
 if not exists(select 1 from knowledge_versions where workflow_run_id=rid) then raise exception 'Workflow provenance missing';end if;
 v:=knowledge_mutate(o,a,'apply_job',sid,jid,null,'{}');if not (v->>'alreadyApplied')::boolean then raise exception 'Duplicate import not blocked';end if;
 v:=knowledge_mutate(o,a,'delete_record',sid,did,2);
 if jsonb_array_length(knowledge_search(o,sid,'research'))<>0 then raise exception 'Archived source still retrievable';end if;
 if not exists(select 1 from knowledge_edges where target_id=did) then raise exception 'Archived evidence lost';end if;
 v:=knowledge_mutate(o,a,'delete_record',sid,kid,1);
 if not exists(select 1 from knowledge_edges where source_id=kid and target_id=did) then raise exception 'Archiving a skill erased its graph provenance';end if;
 bad:=false;begin perform knowledge_mutate(o,a,'save_record',sid,null,null,jsonb_build_object('kind','mapping','name','Archived skill mapping','body',jsonb_build_object('skillId',kid,'framework','F','category','C','level','L')));exception when others then bad:=true;end;if not bad then raise exception 'New mappings accepted an archived skill';end if;
 delete from workflow_runs where id=rid;
 if not exists(select 1 from knowledge_versions where workflow_run_id=rid) then raise exception 'Run retention erased provenance IDs';end if;
 if (select run_id from knowledge_jobs where id=jid) is not null then raise exception 'Job run pointer not cleared by retention';end if;
 v:=claim_knowledge_job();if v is null or v->>'lease_token' is null then raise exception 'Dispatcher claim failed';end if;
 if (claim_knowledge_job()->>'id')=(v->>'id') then raise exception 'Job lease not exclusive';end if;
end $$;
rollback;
